# Generated by Django 4.0.2 on 2022-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=20)),
                ('Pcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pmfdt', models.DateField()),
                ('Pexpdt', models.DateField()),
            ],
        ),
    ]
